plugins {
    id 'com.android.application'
}

android {
    namespace 'com.miniadbnotify'
    compileSdk 35

    defaultConfig {
        applicationId 'com.miniadbnotify'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "adb-notify_${variant.buildType.name}.apk"
        }
    }
}
