plugins {
    id 'com.android.application'
}

android {
    namespace 'com.indevice.adb'
    compileSdk 35

    defaultConfig {
        applicationId 'com.indevice.adb'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "indevice-adb_${variant.buildType.name}.apk"
        }
    }
}

dependencies {
    implementation('androidx.activity:activity:1.9.3') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
}
